[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=app

[program:gateway]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/app/gateway
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=INGESTION_BASE_URL="http://localhost:8086",EVIDENCE_BASE_URL="http://localhost:8087"

[program:ingestion]
command=uvicorn app.main:app --host 0.0.0.0 --port 8086
directory=/app/ingestion
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CACHE_BASE_URL="http://localhost:8091"

[program:evidence]
command=uvicorn app.main:app --host 0.0.0.0 --port 8087
directory=/app/evidence
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CACHING_LAYER_BASE_URL="http://localhost:8091"

[program:caching]
command=uvicorn app.main:app --host 0.0.0.0 --port 8091
directory=/app/caching
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
